### ISSUE TITLE
Что делать если не работают некоторые сайты

### ISSUE THREAD

**Issue by SimePel** [SimePel/asu-monitoring#1]
В readme написано, что если некоторые сайты из списка не отвечают, то индикатор следует покрасить в желтый и нерабочие сайты отобразить. Так как фронтенд это не мое, то спрашиваю у всех остальных, может есть какие-нибудь идеи?

**Comment by pavel1000** [comment]
Я уточню, у тебя вопрос по самой "идее индикации"? Если так, то по моему тут лучше не сделать.
Или тебя интересует реализация?

**Comment by SimePel** [comment]
Мне пока не понятно как отобразить сайты не работающие. Тупо в строчку? хотелось бы как-нибудь красиво

**Comment by pavel1000** [comment]
Я думаю изменения цвета иконок будет достаточно.
Можно в каком-нибудь отдельном блоке выводить неработающие. Например в блок с красной рамкой ( или что-то проде того) помещать нерабочие сайты.
