### ISSUE TITLE
Поправить положение логотипа АГУ

### ISSUE THREAD

**Issue by SimePel** [SimePel/asu-monitoring#2]
Мне кажется, что логотип можно сделать по центру относительно текста слева. Сейчас он прижат к верху и по-моему выглядит не очень эстетично. Хотелось бы чтобы и текст и логотип были на одном уровне.

**Comment by pavel1000** [comment]
добавь в main.css : 

.level {
    margin: 2% auto;
}

**Comment by pavel1000** [comment]
Вообще там ещё несколько моментов:
-логотип немного выезжает за пределы своего блока (вниз немного высовывается, не особо заметно, но есть такое), зато логотип более естественно выглядит (пропорции, вроде, сохраняются);
-на позиционирование при изменении ширины браузера влияет св-во "is-4". При его изменении меняется размер текста, но при этом как-то странно логотип и заголовок съезжают при ограниченной ширине.
* и ещё страница не полностью покрывает высоту окна, особенно заметно при добавлении фона. Можно для html добавить св-во heigh:100%, но из-за каких-то других влияний размер body всё равно получается меньше))
** фон можно добавить, например, такой:

html {
    height: 100%;
    background: linear-gradient(to top left, rgba(190, 59, 99, 0.8), rgba(55, 95, 133, 0.5));
}

**Comment by SimePel** [comment]
Спасибо за ответики. Отправляй пул реквесты с изменениями я посмотрю и по возможности добавлю.
